server {
    # Internal container port
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    # Compression
    gzip on;

    # gzip_vary on — добавлять заголовок Vary: Accept-Encoding
    # So that proxy servers (CDN, caches) know:
    #   "this response can be in both compressed and uncompressed form"
    #   "cache both versions separately"
    gzip_vary on;

    # compress only responses longer than 1024 bytes
    gzip_min_length 1024;

    # compress all text types
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/xml+rss
        application/json;

    # Efficiently send files to the client
    sendfile on;
    tcp_nopush on;

    # Security

    # hide nginx version in responses
    server_tokens off;

    # prevent iframe embedding
    add_header X-Frame-Options "SAMEORIGIN" always;

    # prevent browser from guessing content type
    add_header X-Content-Type-Options "nosniff" always;

    # enable built-in XSS filter in browser
    add_header X-XSS-Protection "1; mode=block" always;

    # Caching and routing
    # Assets gain unique names for each build so we can cache them forever
    # If files are changed, they will have a new name and will be cached again
    location /assets/ {
        # cache files for 1 year
        expires 1y;
        # cache files for public use
        add_header Cache-Control "public, immutable";
        # disable logging for these requests
        access_log off;
    }

    # Handle all requests that did not match other locations
    location / {
        # try to find the exact file or directory, otherwise return 404
        try_files $uri $uri/ =404;
        # never cache these requests
        add_header Cache-Control "no-store";
    }

    # Return 404 page for 404 errors
    error_page 404 /404.html;

    # Disallow direct access to 404 page
    location = /404.html {
        internal;
        add_header Cache-Control "no-store";
    }

    # Hidden files and directories
    # Disallow access to hidden files and directories
    # Use regular expression to match all files and directories starting with a dot
    location ~ /\. {
        deny all;
        # disable logging for these requests
        access_log off;
        # disable logging for not found files
        log_not_found off;
    }
}
